import * as ReactPDF from '@react-pdf/renderer'

const { StyleSheet } = ReactPDF

export const styles = StyleSheet.create({
  page: {
    paddingHorizontal: 56,
    paddingTop: 36,
    paddingBottom: 56,
    fontFamily: 'Helvetica',
    fontSize: 9.25,
    color: '#172033',
    backgroundColor: '#fbfcfe',
  },
  coverPage: {
    paddingHorizontal: 62,
    paddingTop: 52,
    paddingBottom: 52,
    fontFamily: 'Helvetica',
    fontSize: 10,
    color: '#172033',
    backgroundColor: '#fbfcfe',
  },
  coverHairline: {
    width: 52,
    height: 3,
    backgroundColor: '#18a3a8',
    marginBottom: 20,
  },
  header: {
    marginBottom: 28,
    alignItems: 'flex-start',
  },
  coverContent: {
    flexGrow: 1,
    justifyContent: 'space-between',
  },
  runningHeader: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginBottom: 26,
    paddingBottom: 11,
    borderBottomWidth: 1,
    borderBottomColor: '#dde3eb',
  },
  pageBrand: {
    alignItems: 'flex-start',
  },
  pageBrandIcon: {
    width: 18,
    height: 18,
    objectFit: 'contain',
  },
  logo: {
    width: 128,
    height: 28,
    objectFit: 'contain',
    marginBottom: 28,
  },
  titleBlock: {
    alignItems: 'flex-start',
    maxWidth: 420,
  },
  titlePrefix: {
    fontSize: 23,
    fontWeight: 700,
    lineHeight: 1.06,
    color: '#111827',
    textAlign: 'left',
  },
  titleProcess: {
    fontSize: 24,
    fontWeight: 700,
    color: '#18a3a8',
    textAlign: 'left',
    lineHeight: 1.12,
    marginTop: 10,
  },
  subtitle: {
    fontSize: 8.5,
    color: '#697386',
    textAlign: 'left',
    marginTop: 16,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#d8dee8',
    lineHeight: 1.3,
  },
  coverIntroPanel: {
    marginTop: 'auto',
    paddingTop: 18,
    borderTopWidth: 1,
    borderTopColor: '#d8dee8',
  },
  issuedLine: {
    marginTop: 10,
    fontSize: 8.5,
    color: '#4b5563',
    lineHeight: 1.3,
  },
  section: {
    marginBottom: 18,
    paddingTop: 1,
  },
  sectionTitle: {
    fontSize: 12.5,
    fontWeight: 700,
    color: '#111827',
    marginBottom: 10,
    paddingBottom: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#18a3a8',
  },
  sectionLead: {
    marginTop: 8,
    marginBottom: 0,
    color: '#3f4b5f',
    lineHeight: 1.3,
  },
  keyValueTable: {
    borderWidth: 1,
    borderColor: '#dfe5ee',
    borderRadius: 2,
    overflow: 'hidden',
    backgroundColor: '#ffffff',
    marginBottom: 10,
  },
  fieldRow: {
    flexDirection: 'row',
    gap: 14,
    paddingVertical: 6.5,
    paddingHorizontal: 9,
    borderBottomWidth: 1,
    borderBottomColor: '#edf1f6',
    alignItems: 'flex-start',
  },
  fieldRowStacked: {
    flexDirection: 'column',
    gap: 3,
    paddingVertical: 6.5,
    paddingHorizontal: 9,
    borderBottomWidth: 1,
    borderBottomColor: '#edf1f6',
  },
  lastFieldRow: {
    borderBottomWidth: 0,
  },
  fieldLabel: {
    width: '37%',
    fontWeight: 700,
    color: '#4b5563',
    fontSize: 8,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  fieldValue: {
    flexGrow: 1,
    flexShrink: 1,
    minWidth: 0,
    width: '63%',
    color: '#172033',
    wordBreak: 'break-all',
  },
  fieldValueStacked: {
    width: '100%',
    color: '#172033',
  },
  fieldHelperText: {
    marginTop: 3,
    fontSize: 7.6,
    lineHeight: 1.35,
    color: '#5f6b7a',
  },
  linkValueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 1.5,
  },
  linkValueText: {
    flexGrow: 1,
    flexShrink: 1,
    minWidth: 0,
    color: '#0f7f86',
    fontWeight: 700,
    wordBreak: 'break-all',
  },
  paragraph: {
    marginBottom: 7.5,
    color: '#2f3a4c',
    lineHeight: 1.1,
  },
  afterBoxText: {
    marginTop: 1,
  },
  italicText: {
    fontStyle: 'italic',
  },
  bulletRow: {
    flexDirection: 'row',
    gap: 9,
    marginBottom: 4.5,
  },
  bulletMarker: {
    width: 10,
    flexShrink: 0,
    color: '#18a3a8',
    fontWeight: 700,
  },
  bulletText: {
    flex: 1,
    color: '#2f3a4c',
  },
  questionCard: {
    marginTop: 12,
    marginBottom: 10,
    paddingVertical: 12,
    paddingHorizontal: 13,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#e1e7ef',
    borderRadius: 3,
    backgroundColor: '#ffffff',
  },
  questionTitle: {
    fontSize: 11,
    fontWeight: 700,
    color: '#111827',
    marginBottom: 5,
  },
  questionMeta: {
    fontSize: 8.5,
    color: '#5f6b7a',
    marginBottom: 5,
  },
  questionResultsLabel: {
    fontSize: 8,
    color: '#697386',
    marginTop: 4,
    marginBottom: 5,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  questionSummaryRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 8,
  },
  questionSummaryPill: {
    flexGrow: 1,
    flexBasis: '30%',
    minWidth: 0,
    paddingVertical: 4.5,
    paddingHorizontal: 7,
    backgroundColor: '#f3f6fa',
    borderRadius: 2,
  },
  questionSummaryVotesPill: {
    width: '30%',
  },
  questionSummaryOutcomePill: {
    width: '66%',
    flexShrink: 1,
    minWidth: 0,
  },
  questionSummaryLabel: {
    fontSize: 7.25,
    color: '#697386',
    textTransform: 'uppercase',
    letterSpacing: 0.35,
    marginBottom: 2,
  },
  questionSummaryValue: {
    fontSize: 8.75,
    color: '#172033',
    fontWeight: 700,
    lineHeight: 1.25,
  },
  questionOutcome: {
    fontSize: 8.5,
    color: '#172033',
    marginTop: 7,
    paddingTop: 6,
    borderTopWidth: 1,
    borderTopColor: '#edf1f6',
  },
  indexIntro: {
    marginBottom: 14,
    color: '#4b5563',
    lineHeight: 1.3,
  },
  indexRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    minHeight: 30,
    paddingVertical: 7,
  },
  indexLabel: {
    flexShrink: 0,
    paddingRight: 8,
    fontSize: 9.5,
    lineHeight: 1.25,
    color: '#172033',
  },
  indexLeader: {
    flexGrow: 1,
    flexShrink: 1,
    height: 1,
    marginRight: 8,
    marginBottom: 2,
    borderBottomWidth: 1,
    borderBottomStyle: 'dotted',
    borderBottomColor: '#a8b3c2',
  },
  indexPage: {
    width: 20,
    textAlign: 'right',
    color: '#172033',
    fontSize: 9,
    fontWeight: 400,
  },
  indexLink: {
    color: '#172033',
    textDecoration: 'none',
  },
  resultTable: {
    borderTopWidth: 1,
    borderTopColor: '#e1e7ef',
  },
  resultHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 5,
    borderBottomWidth: 1,
    borderBottomColor: '#e8edf4',
  },
  resultHeaderOption: {
    width: '64%',
    fontSize: 7.25,
    fontWeight: 700,
    color: '#697386',
    textTransform: 'uppercase',
    letterSpacing: 0.45,
  },
  resultHeaderOptionWeighted: {
    width: '40%',
  },
  resultHeaderVotes: {
    width: '13%',
    fontSize: 7.25,
    fontWeight: 700,
    textAlign: 'right',
    color: '#697386',
    textTransform: 'uppercase',
    letterSpacing: 0.45,
  },
  resultHeaderVotesWeighted: {
    width: '16%',
  },
  resultHeaderShare: {
    width: '17%',
    fontSize: 7.25,
    fontWeight: 700,
    textAlign: 'right',
    color: '#697386',
    textTransform: 'uppercase',
    letterSpacing: 0.45,
  },
  resultHeaderShareWeighted: {
    width: '18%',
  },
  resultHeaderEligibleShare: {
    width: '20%',
    fontSize: 7.25,
    fontWeight: 700,
    textAlign: 'right',
    color: '#697386',
    textTransform: 'uppercase',
    letterSpacing: 0.45,
  },
  resultRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 6.25,
    borderBottomWidth: 1,
    borderBottomColor: '#edf1f6',
  },
  resultOptionCell: {
    width: '64%',
  },
  resultOptionCellWeighted: {
    width: '40%',
  },
  resultValueCell: {
    width: '13%',
  },
  resultValueCellWeighted: {
    width: '16%',
  },
  resultShareCell: {
    width: '17%',
  },
  resultShareCellWeighted: {
    width: '18%',
  },
  resultEligibleShareCell: {
    width: '20%',
  },
  resultChoiceName: {
    fontSize: 8.7,
    color: '#2f3a4c',
    marginBottom: 4,
  },
  resultValueText: {
    fontSize: 8.75,
    color: '#111827',
    textAlign: 'right',
    fontWeight: 700,
  },
  resultShareText: {
    fontSize: 8.5,
    color: '#3f4b5f',
    textAlign: 'right',
  },
  resultBarTrack: {
    height: 4,
    width: '100%',
    backgroundColor: '#edf2f7',
    borderRadius: 2,
  },
  resultBarFill: {
    height: 4,
    backgroundColor: '#18a3a8',
    borderRadius: 2,
  },
  legalNotice: {
    marginTop: 'auto',
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#d8dee8',
  },
  pageFooter: {
    position: 'absolute',
    left: 56,
    right: 56,
    bottom: 39,
    borderTopWidth: 1,
    borderTopColor: '#c7d0dd',
  },
  pageNumber: {
    position: 'absolute',
    bottom: 22,
    left: 56,
    right: 56,
  },
  pageNumberText: {
    textAlign: 'center',
    color: '#111827',
    fontSize: 11,
    fontWeight: 700,
  },
  footerTitle: {
    fontSize: 8.5,
    fontWeight: 700,
    color: '#111827',
    marginBottom: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  footerParagraph: {
    fontSize: 7.25,
    color: '#4b5563',
    marginBottom: 3,
    lineHeight: 1.25,
  },
  smallText: {
    fontSize: 9,
    color: '#697386',
  },
  // Zero-size invisible text node used as a layout probe to capture the PDF page number
  // a section block lands on. Must NOT include lineHeight (react-pdf v4 render-prop constraint).
  captureProbe: {
    fontSize: 0,
    height: 0,
    position: 'absolute',
  },
})
